#!/usr/bin/env bash
# 生成 resources-inline.js：将所有 md / json / css 资源以路径→字符串的形式打入
# window.__QUI_RES__，使 component-matrix.html 在 file:// 协议下也能读取 Markdown / JSON / CSS 视图
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

python3 - "$ROOT" <<'PY'
import os, sys, json, glob
root = sys.argv[1]
os.chdir(root)
paths = []
for pat in ("md/*.md", "md/**/*.md", "json/**/*.json", "css/*.css"):
    paths.extend(glob.glob(pat, recursive=True))
paths = sorted(set(paths))
bag = {}
for p in paths:
    with open(p, "r", encoding="utf-8") as f:
        bag[p] = f.read()
body = (
    "/* Auto-generated by build-inline-resources.sh — do not edit manually. */\n"
    "window.__QUI_RES__ = " + json.dumps(bag, ensure_ascii=False) + ";\n"
)
with open("resources-inline.js", "w", encoding="utf-8") as f:
    f.write(body)
print(f"[ok] Wrote {len(bag)} files -> resources-inline.js ({len(body):,} bytes)")
PY
